// Reads the localhost deployment artifacts and writes web/.env.local
// so the frontend points at the freshly-deployed local mocks. Run after
// `hardhat deploy --network localhost --tags test`.
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const DEPLOYMENTS = path.resolve(__dirname, '../deployments/localhost')
const WEB_ENV = path.resolve(__dirname, '../../web/.env.local')

// deployment artifact name -> NEXT_PUBLIC_* var
const MAP = {
	StreamVaults: 'NEXT_PUBLIC_STREAM_VAULTS_ADDRESS',
	StreamVaultsConfig: 'NEXT_PUBLIC_STREAM_VAULTS_CONFIG_ADDRESS',
	SmartAccountRegistry: 'NEXT_PUBLIC_SMART_ACCOUNT_REGISTRY_ADDRESS',
	MockCFAv1Forwarder: 'NEXT_PUBLIC_CFA_FORWARDER_ADDRESS',
	MockSuperToken: 'NEXT_PUBLIC_USDCX_ADDRESS',
	MockERC20Permit: 'NEXT_PUBLIC_USDC_ADDRESS',
	MockMintableERC20: 'NEXT_PUBLIC_WETH_ADDRESS',
	MockUniswapRouter: 'NEXT_PUBLIC_ROUTER_ADDRESS'
}

function readAddress(name) {
	const file = path.join(DEPLOYMENTS, `${name}.json`)
	const json = JSON.parse(fs.readFileSync(file, 'utf-8'))
	return json.proxy ?? json.address
}

// Parse the existing .env.local (if any) so we can preserve vars we don't
// manage — most importantly NEXT_PUBLIC_REOWN_PROJECT_ID, which lives only
// here (it's gitignored). Without this, every redeploy wiped it.
const managed = new Set([
	'NEXT_PUBLIC_LOCAL_RPC_URL',
	...Object.values(MAP)
])
const preserved = []
if (fs.existsSync(WEB_ENV)) {
	for (const raw of fs.readFileSync(WEB_ENV, 'utf-8').split('\n')) {
		const line = raw.trim()
		if (!line || line.startsWith('#')) continue
		const key = line.slice(0, line.indexOf('=')).trim()
		if (key && !managed.has(key)) preserved.push(raw)
	}
}

const lines = ['# Auto-generated by scripts/sync-web-env.mjs — local Hardhat addresses']
lines.push('NEXT_PUBLIC_LOCAL_RPC_URL=http://127.0.0.1:8545')
for (const [name, envVar] of Object.entries(MAP)) {
	lines.push(`${envVar}=${readAddress(name)}`)
}
if (preserved.length > 0) {
	lines.push('# --- preserved (not managed by sync-web-env) ---')
	lines.push(...preserved)
}

fs.writeFileSync(WEB_ENV, lines.join('\n') + '\n')
console.log(`[sync-web-env] wrote ${WEB_ENV}`)
for (const line of lines.slice(1)) console.log('  ' + line)
if (preserved.length === 0) {
	console.log(
		'[sync-web-env] note: no NEXT_PUBLIC_REOWN_PROJECT_ID found — wallet connect needs it.'
	)
}
